[project]
name = "wxreader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.2",
    "nuitka>=2.8.9",
    "numpy>=2.3.5",
    "pymupdf==1.23.8",
    "pyopengl>=3.1.10",
    "pyvips>=3.1.1",
    "pywinstyles>=1.8",
    "pyzipper>=0.3.6",
    "wxpython>=4.2.4",
]

[project.optional-dependencies]
analysis = [
    "jinja2>=3.1.6",
    "lizard>=1.19.0",
    "radon>=6.0.1",
    "viztracer>=1.1.1",
]
